# TODOs
# 1) Minior improvements
#    * Add an appveyor status badge (https://www.appveyor.com/docs/status-badges/), similar to the used travis status badge
# 2) Make Eigen work
#    * Change appveyor.yml so that the library Eigen can be used on appveyor (probably, one has to make appveyor download Eigen from bitbuckets)
#    * Adapt the file cmake/FindEigen3.cmake so that the command "find_package(Eigen3 REQUIRED)" in the file CMakeLists.txt works on appveyor as well
##   * Uncomment the Eigen example in Source.cpp and let it run

## EIGEN CHANGS

#  The latest stable release is Eigen 3.3.3.
#   http://bitbucket.org/eigen/eigen/get/3.3.3.zip
#  - ps: wget http://bitbucket.org/eigen/eigen/get/3.3.3.zip     -OutFile eigen.zip
#  - cmd: 7z x eigen.zip -o"C:\projects" -y > nul
#
# Changes to  be done in CMakeLists.txt..
# http://stackoverflow.com/questions/12249140/find-package-eigen3-for-cmake
# https://eigen.tuxfamily.org/dox/TopicCMakeGuide.html
# http://stackoverflow.com/questions/34138879/unable-to-find-eigen3-with-cmake
# 
#in before build
#   - cmd: cmake -G "Visual Studio 14 2015 Win64" -D EIGEN3_INCLUDE_DIR=C:\projects\
#  DCMAKE_MODULE_PATH=C:\projects\cmakevisualstudio\cmake\
###################################################
# all the Find ***.cmake files related packages
#find_package(Git REQUIRED)
#find_package(Eigen3 REQUIRED) ok
#find_package(Sqlite3 REQUIRED)
#find_package(Boost COMPONENTS filesystem system program_options REQUIRED) ok
#find_package(GSL REQUIRED).. Ok
#find_package(OpenMP REQUIRED).. Ok
#find_package(PythonInterp 3 REQUIRED)
#find_package(PyUIC REQUIRED)
#
#http://stackoverflow.com/questions/41640029/how-can-i-link-cmake-and-sqlite-without-an-external-script
#http://stackoverflow.com/questions/1359793/programmatically-extract-tar-gz-in-a-single-step-on-windows-with-7zip
#https://bitbucket.org/amontalenti/appveyor-test/overview
#https://github.com/ContinuumIO/anaconda-issues/issues/438


os: Visual Studio 2015

platform: x64

configuration: Release

environment:
    #EIGEN3_ROOT:  C:\Program Files\eigen3
    #BOOST_ROOT: C:\Libraries\boost_1_63_0
    #BOOST_LIBRARYDIR: C:\Libraries\boost_1_63_0\lib64-msvc-14_0
    #SQLITE3_ROOT: C:\Program Files\sqlite
    PYTHON_ROOT: C:\Python36-x64
    PYTHON_VERSION: 3.6
    #GSL_INCLUDEDIR: C:\Program Files\gsl
    #GSL_LIBDIR: C:\Program Files\gsl
    MINICONDA: C:\Miniconda36-x64
    SWIG_ROOT:
    
 
install:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  
  # USING VCPKG FOR INSTALLING STANDARD LIBRARIES
  - cmd: >-
        cd C:\
        
        IF NOT EXIST c:\vcpkg\ ( git clone https://github.com/Microsoft/vcpkg ) ELSE ( echo VCPKG is cached )
        
        cd vcpkg
        
        dir
        
        powershell -exec bypass scripts\bootstrap.ps1

        .\vcpkg integrate install
        
        .\vcpkg install sqlite3:x64-windows eigen3
  
  # To install the eigen in home directory using PowerShell
  #- ps: wget http://bitbucket.org/eigen/eigen/get/3.3.3.zip     -OutFile eigen.zip
  #- cmd: 7z x eigen.zip -o"C:\Program Files" -y > nul
  #- ps: Rename-Item -Path "C:/Program Files/eigen-eigen-67e894c6cd8f" -NewName "C:/Program Files/eigen3"
  
  # To install the sqlite in home directory using PowerShell
  #- ps : wget http://www.sqlite.org/2017/sqlite-dll-win64-x64-3190200.zip   -OutFile Lib.zip
  #- cmd: 7z e Lib.zip -o"C:\Program Files\sqlite" -y > nul
  #- ps : wget http://www.sqlite.org/2017/sqlite-tools-win32-x86-3190200.zip   -OutFile Bin.zip
  #- cmd: 7z e Bin.zip -o"C:\Program Files\sqlite" -y > nul
  #- ps : wget http://www.sqlite.org/2017/sqlite-amalgamation-3190200.zip   -OutFile include.zip
  #- cmd: 7z e include.zip -o"C:\Program Files\sqlite" -y > nul
  #- cmd: lib /def:"C:\Program Files\sqlite\sqlite3.def" /out:"C:\Program Files\sqlite\sqlite3.lib" /machine:x64
  
  # To install the GSL in home directory using PowerShell
  #- ps : wget https://www.bruot.org/hp/media/files/libraries/gsl_1_16_msvc2015_64.zip   -OutFile gsl.zip
  #- cmd: 7z e gsl.zip -o"C:\Program Files\gsl" -y > nul
        
  # To install SWIG in home directory using choco
  #- ps: choco install -y swig > $null
  
  # Using MINICONDA pre installed to setup  pyqt and numpy
  #- cmd: call C:\Miniconda36-x64\Scripts\activate.bat
  
  #- "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  #- conda install --yes --quiet pyqt=5
  # Using MINICONDA pre installed to setup  NumPy
  #- conda install --yes --quiet numpy
  #- cmd: which pkg-config
  - ps: choco install -y sqlite
  
  

before_build:
  - cmd: cd C:/projects/cmakevisualstudio
  - cmd: md build && cd build
  #- cmd: cmake -G "Visual Studio 14 2015 Win64" ..
  
  #- ps: ls "C:/Miniconda36-x64/pkgs/pyqt-5.6.0-py36_2/Library/bin"
  #- ps: ls "C:/Program Files/gsl"
  - ps: ls "C:/projects/cmakevisualstudio"
   
  #- cmd: cmake -G "Visual Studio 14 2015 Win64" -DEIGEN3_INCLUDE_DIR=C:\projects\eigen-eigen-67e894c6cd8f\ ..
  - cmd: cmake -G "Visual Studio 14 2015 Win64" .. -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake"

build:
  project: build\hello.vcxproj
  parallel: true
  verbosity: minimal

artifacts:
  - path: build\Release\hello.exe
    name: installer
    
cache: c:\vcpkg\ -> appveyor.yml    

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token: $(GH_TOKEN)
    artifact:  installer
    prerelease: true
    force_update: true
    on:
      appveyor_repo_tag: true  
  
  

 
